name:                hask-sim-str
version:             0.1.0.0
github:              "eraf2135/hask-sim-str"
license:             BSD3
author:              "Emile Raffoul"
maintainer:          "emile.raffoul@gmail.com"
copyright:           "2018 Emile Raffoul"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eraf2135/hask-sim-str#readme>

dependencies:
- base >= 4.7 && < 5
- edit-distance == 0.2.2.1
- hspec == 2.5.5
- QuickCheck ==2.11.3

library:
  source-dirs: src

executables:
  hask-sim-str-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-sim-str

tests:
  hask-sim-str-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-sim-str
